name: Continuous Deployment
on:
  push:
    branches:
      - main

jobs:
  Build-And-Deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CD build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"
      - run: echo "TODO Deploy to stage environment?"
      - run: echo "TODO Send Slack notification on failures?"
      - run: echo "TODO Send Slack notification on new PR?"
  call-build:
    name: Build and Upload
    uses: eclipse-pass/playground/.github/workflows/build.yml@main
