name: Playground Continuous Integration
on: [pull_request]

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  call-test-maven-jar:
    name: Run Automated Tests - Maven JAR
    uses: eclipse-pass/playground/.github/workflows/maven-jar-test.yml@56509e3819434a8bf283580f5bbc0c3ea65d77c0

  call-test-maven-service:
    name: Run Automated Tests - Maven service
    uses: eclipse-pass/playground/.github/workflows/maven-service-test.yml@56509e3819434a8bf283580f5bbc0c3ea65d77c0

  temp-call-html-app-publish:
    name: TEMP - run html-app publish step for testing
    uses: eclipse-pass/playground/.github/workflows/html-app-publish.yml@56509e3819434a8bf283580f5bbc0c3ea65d77c0
