name: Playground Continuous Integration
on: [pull_request]

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  call-test-maven-jar:
    name: Run Automated Tests - Maven JAR
    uses: eclipse-pass/playground/.github/workflows/maven-jar-test.yml@main

  call-test-maven-service:
    name: Run Automated Tests - Maven service
    uses: eclipse-pass/playground/.github/workflows/maven-service-test.yml@main

  call-lint-emberjs-app:
    name: Run Lint - EmberJS
    uses: eclipse-pass/playground/.github/workflows/emberjs-app-lint.yml@main

  call-test-emberjs-app:
    name: Run Automated Tests - EmberJS
    uses: eclipse-pass/playground/.github/workflows/emberjs-app-test.yml@main

  temp-call-publish-docker:
    name: Build and Publish Docker image
    uses: eclipse-pass/playground/.github/workflows/html-app-publish.yml@eb0055984165ee2f5e00a6c80ee52491d904f203
