name: Run Automated Tests - EmberJS
on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
          cache: npm
          cache-dependency-path: emberjs-app/package-lock.json
      - name: Install Dependencies
        run: cd emberjs-app && npm ci
      - name: Run Tests
        run: cd emberjs-app && npm test
