name: Run Automated Tests - EmberJS
on: [workflow_call, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          #TODO: Verify Node version
          node-version: 12.x
          cache: npm
          cache-dependency-path: emberjs-app/package-lock.json
      - name: Build project
        run: cd emberjs-app && yarn install --frozen-lockfile
      - name: Run Tests
        run: cd emberjs-app && ./node_modules/ember-cli/bin/ember test --test-port=4200
