name: Run Lint - EmberJS
on:
  workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          #TODO: Verify Node version
          node-version: 12.x
          cache: npm
          cache-dependency-path: emberjs-app/package-lock.json
      - name: Install Dependencies
        run: cd emberjs-app && npm ci
      - name: Lint
        run: cd emberjs-app && npm run lint
