name: Publish Package - Maven Service
on: [workflow_call, workflow_dispatch]

jobs:
  publish-maven:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      packages: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          #TODO: Verify Java version
          java-version: 14
      - name: Publish maven-service package
        run: cd ${{ github.workspace }}/maven-service && mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
