# This workflow will update the pass-core-main Docker image in GHCR and update the pass-core config
#   in pass-docker

name: Update pass-docker test

on:
  workflow_dispatch:
    inputs:
      pomVersion:
        description: 'Version that would appear in pom file'
        required: true
        default: '0.2.0-SNAPSHOT'


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout current repo
      - name: Check out latest playground
        uses: actions/checkout@v2

      # Update pass-core config in pass-docker
      - name: Return to root folder
        run: cd ..
      - name: Check out pass-docker
        uses: actions/checkout@v2
        with:
          repository: eclipse-pass/pass-docker
          token: ${{ secrets.pass_docker_pat }}
      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: ${{ secrets.pass_docker_pat }}
      - name: Get pom version
        id: pom_version
        run: echo "POM_VERSION=${{ github.event.inputs.pomVersion }}" >> $GITHUB_OUTPUT
      - name: Update nightly server config
        run: python tools/update-image.py eclipse-pass.nightly.yml pass-core ${{ steps.pom_version.outputs.POM_VERSION }}
      - name: Commit change (if any)
        # The 'git diff --quiet' ensures that the add/commit is only attempted if there is a change
        run: git diff --quiet || git commit -am 'Update pass-core image to ${{ steps.pom_version.outputs.POM_VERSION }}'
      - name: Push update
        run: git push
